### ISSUE TITLE
Gravity doesn't work as expected

### ISSUE THREAD

**Issue by Fusl** [fph/bastet#7]
![ba82c013d24e](https://user-images.githubusercontent.com/2349496/31579404-c3000882-b135-11e7-9d67-c020b284ff42.png)
The floating red block down there should actually be falling down due to gravity actually existing: https://gamedevelopment.tutsplus.com/tutorials/implementing-tetris-clearing-lines--gamedev-1197

**Comment by fph** [comment]
Hi and thanks for your bug reports (and for the patch).

Regarding this issue: my experience is that most Tetris implementations would leave the red dot where it is, and the reference in your link agrees:

> It's not wrong, exactly - most versions of Tetris do this, including the classic Game Boy edition - so you could leave it at that.

Also there is nothing about it in the [Tetris guidelines](http://tetris.wikia.com/wiki/Tetris_Guideline), which just states

> If this results in one or more complete 10-cell rows in the Matrix becoming unoccupied by Minos, then
all Minos above that row(s) collapse, or fall by the number of complete rows cleared from the
Matrix.

So I would close this as WONTFIX, unless you have additional arguments.

**Comment by Fusl** [comment]
> > including the classic Game Boy edition
Oh, ok, didn't see that part when I read the article.

> So I would close this as WONTFIX, unless you have additional arguments

Yes, please close as wontfix 👍
